"use client";
import React, { Suspense } from "react";
import { Inter } from "next/font/google";
import Header from "./components/Header";
import { useTranslation } from "react-i18next";
import "./i18n";
import "./globals.css";
import Loading from "./Loading";
const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Atefeh Karimi Kia Portfolio",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const { i18n } = useTranslation();
  return (
    <html>
      <body className={inter.className}>
        <Suspense fallback={<Loading />}>
          <div className={`${i18n.language === "fa" ? "rtl" : ""} `}>
            <Header />
            {children}
          </div>
        </Suspense>
      </body>
    </html>
  );
}
